DELIMITER $$

CREATE PROCEDURE sp_errores_varios1()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42S02'
    SELECT 'SQLSTATE Tabla no existe' AS error;
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    SELECT 'SQLEXCEPTION Tabla no existe' AS error;

  DROP TABLE tabla_no_existe;
END;$$

DELIMITER ;